# Generated by Django 5.1 on 2024-08-09 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('price', models.FloatField(verbose_name=django.core.validators.MinValueValidator(0))),
                ('author', models.CharField(max_length=72)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Publised')], default='draft', max_length=100)),
            ],
        ),
    ]
