# Generated by Django 4.2.13 on 2024-07-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("value", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
