# Generated by Django 4.2.13 on 2024-07-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.URLField(max_length=2083, null=True),
        ),
    ]
