# Generated by Django 5.1 on 2024-08-23 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.RemoveField(
            model_name='library',
            name='book_count',
        ),
    ]
